description = "Manage Focus time"
prompt = """

- Focus time entries: When creating new focus time events, always set colorId to "5" (yellow). When displaying focus time events that don't have color ID 5, automatically update them to use color ID "5".

"""